CREATE TABLE [dbo].[AdrConfiguration] (
    [AdrConfigurationId]              INT            IDENTITY (1, 1) NOT NULL,
    [CredentialCheckLeadDays]         INT            DEFAULT ((7)) NOT NULL,
    [ScrapeRetryDays]                 INT            DEFAULT ((5)) NOT NULL,
    [MaxRetries]                      INT            DEFAULT ((5)) NOT NULL,
    [DailyStatusCheckDelayDays]       INT            DEFAULT ((1)) NOT NULL,
    [MaxParallelRequests]             INT            DEFAULT ((8)) NOT NULL,
    [BatchSize]                       INT            DEFAULT ((1000)) NOT NULL,
    [DefaultWindowDaysBefore]         INT            DEFAULT ((5)) NOT NULL,
    [DefaultWindowDaysAfter]          INT            DEFAULT ((5)) NOT NULL,
    [AutoCreateTestLoginRules]        BIT            DEFAULT ((1)) NOT NULL,
    [AutoCreateMissingInvoiceAlerts]  BIT            DEFAULT ((1)) NOT NULL,
    [MissingInvoiceAlertEmail]        NVARCHAR (255) NULL,
    [IsOrchestrationEnabled]          BIT            DEFAULT ((1)) NOT NULL,
    [Notes]                           NVARCHAR (MAX) NULL,
    [CreatedDateTime]                 DATETIME2 (7)  DEFAULT (getutcdate()) NOT NULL,
    [CreatedBy]                       NVARCHAR (200) DEFAULT ('System') NOT NULL,
    [ModifiedDateTime]                DATETIME2 (7)  DEFAULT (getutcdate()) NOT NULL,
    [ModifiedBy]                      NVARCHAR (200) DEFAULT ('System') NOT NULL,
    [IsDeleted]                       BIT            DEFAULT ((0)) NOT NULL,
    [JobRetentionMonths]              INT            DEFAULT ((12)) NOT NULL,
    [JobExecutionRetentionMonths]     INT            DEFAULT ((12)) NOT NULL,
    [AuditLogRetentionDays]           INT            DEFAULT ((90)) NOT NULL,
    [IsArchivalEnabled]               BIT            DEFAULT ((1)) NOT NULL,
    [ArchivalBatchSize]               INT            DEFAULT ((5000)) NOT NULL,
    [ArchiveRetentionYears]           INT            DEFAULT ((7)) NOT NULL,
    [LogRetentionDays]                INT            DEFAULT ((30)) NOT NULL,
    [MaxOrchestrationDurationMinutes] INT            DEFAULT ((240)) NOT NULL,
    [DatabaseCommandTimeoutSeconds]   INT            DEFAULT ((600)) NOT NULL,
    [TestModeEnabled]                 BIT            DEFAULT ((0)) NOT NULL,
    [TestModeMaxScrapingJobs]         INT            DEFAULT ((50)) NOT NULL,
    [TestModeMaxRebillJobs]           INT            DEFAULT ((50)) NOT NULL,
    [ErrorNotificationsEnabled]       BIT            DEFAULT ((1)) NOT NULL,
    [ErrorNotificationRecipients]     NVARCHAR (500) NULL,
    [OrchestrationNotificationsEnabled] BIT          DEFAULT ((1)) NOT NULL,
    [OrchestrationNotificationRecipients] NVARCHAR (500) NULL,
    CONSTRAINT [PK_AdrConfiguration] PRIMARY KEY CLUSTERED ([AdrConfigurationId] ASC)
);

